files:
  include: 'resources/sass/**/*.s+(a|c)ss'
rules:
  attribute-quotes: 2
  border-zero: 2
  class-name-format: 2
  declarations-before-nesting: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  final-newline: 2
  indentation: 2
  mixins-before-declarations: 0
  nesting-depth:
    - 2
    -
      max-depth: 6
  no-color-keywords: 2
  no-color-literals:
    - 2
    -
      allow-rgba: true
  no-css-comments: 0
  no-empty-rulesets: 2
  no-important: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  property-sort-order:
  - 2
  -
    order: 'smacss'
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-before-bang: 2
  space-before-colon: 0
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
  quotes:
    - 2
    -
      style: 'single'
